name: ovn-docker-images

on:
  push:
  pull_request:
    branches: [ master ]
    paths: [ "dist/images/Dockerfile*"]

env:
  GO_VERSION: 1.16.3
  REGISTRY: ghcr.io 
  OWNER: astoycos
  REPOSITORY: ovn-kubernetes 
  FEDORA_IMAGE_NAME: ovn-kube-f
  UBUNTU_IMAGE_NAME: ovn-kube-u
  CENTOS_IMAGE_NAME: ovn-kube-c 

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Log in to the GH Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}    
   
    - name: Set up environment
      run: |
        export GOPATH=$(go env GOPATH)
        echo "GOPATH=$GOPATH" >> $GITHUB_ENV
        echo "$GOPATH/bin" >> $GITHUB_PATH

    - name: build ovnkube-binaries copy to context 
      run: | 
        pushd go-controller 
         make 
        popd 

        pushd dist/images
          cp -r ../../go-controller/_output/go/bin/* .
        popd 
    
    - name: generate git-info to write to image
      run: | 
        BRANCH=$(git rev-parse --short "$GITHUB_SHA")
        COMMIT=${GITHUB_REF#refs/heads/}
        pushd dist/images
          echo "ref: ${BRANCH}  commit: ${COMMIT}" > git_info
        popd 
    
    - name: Extract metadata (tags, labels) for fedora ovn-k image
      id: meta-fedora
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPOSITORY }}/${{ env.FEDORA_IMAGE_NAME }}

    - name: Build and push Fedora based Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./dist/images
        file: ./dist/images/Dockerfile.fedora
        push: true
        tags: ${{ steps.meta-fedora.outputs.tags }}
        labels: ${{ steps.meta-fedora.outputs.labels }}

    - name: Extract metadata (tags, labels) for ubuntu ovn-k image
      id: meta-ubuntu
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPOSITORY }}/${{ env.UBUNTU_IMAGE_NAME }}

    - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
      
    - name: Build and push Ubuntu based Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./dist/images
        file: ./dist/images/Dockerfile.ubuntu
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta-ubuntu.outputs.tags }}
        labels: ${{ steps.meta-ubuntu.outputs.labels }}

    - name: Extract metadata (tags, labels) for centos ovn-k image
      id: meta-centos
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPOSITORY }}/${{ env.CENTOS_IMAGE_NAME }}
    
    - name: Build and push Centos based Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./dist/images
        file: ./dist/images/Dockerfile
        push: true
        tags: ${{ steps.meta-centos.outputs.tags }}
        labels: ${{ steps.meta-centos.outputs.labels }}

    
